package dev.fanger.inet.rip.Routing;

public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    Graphic network;

    public Interface() {
        initComponents();
        setupNetwork();
    }

    private void setupNetwork() {
        graphicHolder.removeAll();
        network = new Graphic(graphicHolder.getWidth(), graphicHolder.getHeight(), routeTable);
        graphicHolder.add(network);

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        graphicHolder = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        enableAutoRefreshButton = new javax.swing.JToggleButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        routeTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        numNodesToAdd = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout graphicHolderLayout = new javax.swing.GroupLayout(graphicHolder);
        graphicHolder.setLayout(graphicHolderLayout);
        graphicHolderLayout.setHorizontalGroup(
                graphicHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 520, Short.MAX_VALUE)
        );
        graphicHolderLayout.setVerticalGroup(
                graphicHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 463, Short.MAX_VALUE)
        );

        jButton1.setText("Send RIP");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        jButton2.setText("New Network");
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));

        jButton3.setText("Send random data");
        jButton3.addActionListener(evt -> jButton3ActionPerformed(evt));

        enableAutoRefreshButton.setText("Enable Auto RIP");
        enableAutoRefreshButton.addActionListener(evt -> enableAutoRefreshButtonActionPerformed(evt));

        jSpinner1.setValue(15);
        jSpinner1.addChangeListener(evt -> jSpinner1StateChanged(evt));
        jSpinner1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }

            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSpinner1InputMethodTextChanged(evt);
            }
        });
        jSpinner1.addPropertyChangeListener(evt -> jSpinner1PropertyChange(evt));

        jLabel1.setText("RIP Refresh");

        routeTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        routeTable.setMinimumSize(new java.awt.Dimension(100, 64));
        jScrollPane1.setViewportView(routeTable);

        jButton4.setText("Add Node(s)");
        jButton4.addActionListener(evt -> jButton4ActionPerformed(evt));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("100Mbps");
        jRadioButton1.addActionListener(evt -> jRadioButton1ActionPerformed(evt));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("1Gbps");
        jRadioButton2.addActionListener(evt -> jRadioButton2ActionPerformed(evt));

        numNodesToAdd.setValue(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSpinner1))
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jRadioButton1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioButton2))
                                                        .addComponent(enableAutoRefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(81, 81, 81)
                                                .addComponent(numNodesToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4))
                                        .addComponent(graphicHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                                                .addGap(38, 38, 38))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(graphicHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(enableAutoRefreshButton)
                                        .addComponent(jButton2))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton3)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jButton4)
                                        .addComponent(numNodesToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        network.sendOneRip();
    }

    private void formComponentResized(java.awt.event.ComponentEvent evt) {
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        enableAutoRefreshButton.setSelected(false);
        network.mainRefresh.stop();
        setupNetwork();
        setRipTime();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        network.sendRandomPacket();
    }

    private void enableAutoRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {
        network.toggleRIP();
    }

    private void jSpinner1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
    }

    private void jSpinner1PropertyChange(java.beans.PropertyChangeEvent evt) {
    }

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {
        setRipTime();
    }

    private void setRipTime() {
        if (network != null) {
            Integer theValue = (Integer) jSpinner1.getValue();
            if (theValue != null) {
                network.ripExecute = 1.0 * theValue;
            }
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        int numNodes = (int) numNodesToAdd.getValue();
        network.addNodes(numNodes);
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        network.BANDWIDTH = network.BANDWIDTH_100MB;
    }

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        network.BANDWIDTH = network.BANDWIDTH_1GB;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton enableAutoRefreshButton;
    private javax.swing.JPanel graphicHolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner numNodesToAdd;
    private javax.swing.JTable routeTable;

}
